### ISSUE TITLE
Loop will be block here, TFLuna::get_frame_data 

### ISSUE THREAD

**Issue by awong1900** [Seeed-Studio/Seeed_Arduino_TFlidar#1]
https://github.com/Seeed-Studio/Seeed_Arduino_TFlidar/blob/0e85428d3e720ea40fec979e176b77a8f7849551/src/TFLuna/TFLuna.cpp#L64C1-L65C1

```c++
bool TFLuna::get_frame_data(void){
    while(_TFTransporter->read() >= 0);    
    while(!(9 < _TFTransporter->available()));
    uint16_t check;
```

Hi, I found here will be block loop, right? If the serial not come data from Luna, like low frame 1Hz, program will wait long time. 

If you can confirm this issue, we can fix it together.

**Comment by Cincinnatu** [comment]
This seems to be an essential process.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
